## Limpieza de datos

### importar librerias

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("final.csv")

In [5]:
df.head()

,fecha_creacion,latitud,longitud,alcaldia_cierre,colonia_cierre,temp,precip,humedad,viento,radiacion,presion
0,2019-01-03,19.384348,-99.191522,ALVARO OBREGON,SANTA MARIA NONOALCO,12.14,0.00,52.31,0.70,4.4076,74.50
1,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.00,52.31,0.70,4.4076,74.50
2,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.00,52.31,0.70,4.4076,74.50
3,2019-02-02,19.360221,-99.143410,BENITO JUAREZ,PORTALES IV,12.39,0.00,42.04,0.70,5.9741,74.53
4,2019-06-26,19.244516,-99.240369,TLALPAN,HEROES DE 1910,18.72,3.68,74.34,0.65,4.7206,79.94

### Combinar cvs para tener la columna incidente

In [7]:
df2 = pd.read_csv("911_clean.csv")
df["fecha_creacion"] = pd.to_datetime(df["fecha_creacion"])
df2["fecha_creacion"] = pd.to_datetime(df2["fecha_creacion"])

columnas_interes = ["fecha_creacion", "latitud", "longitud", "incidente_c4"]
df1_filtrado = df2[columnas_interes]

new_df = pd.merge(
    df, df1_filtrado, on=["fecha_creacion", "latitud", "longitud"], how="left"
)

new_df.head()

,fecha_creacion,latitud,longitud,alcaldia_cierre,colonia_cierre,temp,precip,humedad,viento,radiacion,presion,incidente_c4
0,2019-01-03,19.384348,-99.191522,ALVARO OBREGON,SANTA MARIA NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
1,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
2,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
3,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
4,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion

#### Convertir tipos de datos

In [9]:
# latitud, longitud y las demas a float
new_df["latitud"] = new_df["latitud"].astype(float)

new_df["longitud"] = new_df["longitud"].astype(float)

new_df["temp"] = new_df["temp"].astype(float)

new_df["precip"] = new_df["precip"].astype(float)

new_df["humedad"] = new_df["humedad"].astype(float)

new_df["viento"] = new_df["viento"].astype(float)

new_df["radiacion"] = new_df["radiacion"].astype(float)

new_df["presion"] = new_df["presion"].astype(float)


# alcaldia_cierre y colonia cierre como str
new_df["alcaldia_cierre"] = new_df["alcaldia_cierre"].str.strip()
new_df["alcaldia_cierre"] = new_df["alcaldia_cierre"].astype(str)

new_df["colonia_cierre"] = new_df["colonia_cierre"].str.strip()
new_df["colonia_cierre"] = new_df["colonia_cierre"].astype(str)

In [10]:
new_df.head()

,fecha_creacion,latitud,longitud,alcaldia_cierre,colonia_cierre,temp,precip,humedad,viento,radiacion,presion,incidente_c4
0,2019-01-03,19.384348,-99.191522,ALVARO OBREGON,SANTA MARIA NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
1,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
2,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
3,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
4,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion

### Verificar que las variables string se puedan convcertir a categoricas para usar para predecir

In [12]:
new_df["alcaldia_cierre"].unique()

array(['ALVARO OBREGON', 'BENITO JUAREZ', 'TLALPAN', 'AZCAPOTZALCO',
       'GUSTAVO A. MADERO', 'LA MAGDALENA CONTRERAS', 'CUAUHTEMOC',
       'VENUSTIANO CARRANZA', 'XOCHIMILCO', 'COYOACAN', 'IZTAPALAPA',
       'IZTACALCO', 'MIGUEL HIDALGO', 'CUAJIMALPA DE MORELOS', 'TLAHUAC',
       'MILPA ALTA'], dtype=object)

In [13]:
new_df["colonia_cierre"].unique()

array(['SANTA MARIA NONOALCO', 'NONOALCO', 'PORTALES IV', ...,
       'BENITO JUAREZ (AMPL)', 'LINDAVISTA VALLEJO (U HAB)',
       'PEON VIEJO (U HAB)'], shape=(1069,), dtype=object)

### Cambiar el nombre de las columnas

In [26]:
new_df = new_df.rename(
    columns = {
        "fecha_creacion" : "fecha",
        "alcaldia_cierre" : "alcaldia",
        "colonia_cierre" : "colonia",
        "incidente_c4" : "incidente"
    }
    
)

In [28]:
new_df.head()

,fecha,latitud,longitud,alcaldia,colonia,temp,precip,humedad,viento,radiacion,presion,incidente
0,2019-01-03,19.384348,-99.191522,ALVARO OBREGON,SANTA MARIA NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
1,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
2,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion
3,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Encharcamiento
4,2019-01-03,19.384560,-99.190621,BENITO JUAREZ,NONOALCO,12.14,0.0,52.31,0.7,4.4076,74.5,Inundacion

### Exportar el csv

In [31]:
new_df.to_csv("data.csv",index=False)